version: "3.1"
services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
    networks:
      - ushnw
  redis:
    image: redis:5-alpine
    networks:
      - ushnw
  platform:
    build: .
    environment:
      APP_KEY: qrBxrvw61b57TUfkYmJFr4pSJr1V8smw
      ENABLE_NGINX: "true"
      ENABLE_PHPFPM: "true"
      ENABLE_PLATFORM_TASKS: "false"
      RUN_PLATFORM_MIGRATIONS: "true"
      DB_CONNECTION: mysql
      DB_DATABASE: ushahidi
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ushahidi
      DB_PASSWORD: ushahidi
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
    command: start
    ports:
      - "8080:8080"
    volumes:
      - storage-app-public:/var/www/storage/app/public
    depends_on:
      - mysql
      - redis
    networks:
      - ushnw
  platform_tasks:
    build: .
    environment:
      APP_KEY: qrBxrvw61b57TUfkYmJFr4pSJr1V8smw
      DOCKERIZE_WAIT_FOR_mysql: tcp://mysql:3306
      DOCKERIZE_WAIT_FOR_redis: tcp://redis:6379
      ENABLE_NGINX: "false"
      ENABLE_PHPFPM: "false"
      ENABLE_PLATFORM_TASKS: "true"
      ENABLE_QUEUE_LISTEN: "true"
      RUN_PLATFORM_MIGRATIONS: "false"
      DB_CONNECTION: mysql
      DB_DATABASE: ushahidi
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ushahidi
      DB_PASSWORD: ushahidi
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
    command: start
    depends_on:
      - mysql
      - redis
    networks:
      - ushnw
    volumes:
      - storage-app-public:/var/www/storage/app/public

volumes:
  # share storage/app/public between platform containers
  storage-app-public:
networks:
  ushnw:
    driver: bridge
